/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcIbox {}
  interface PwcIboxContent {}
  interface PwcIboxFooter {}
  interface PwcIboxTitle {}
}

declare global {


  interface HTMLPwcIboxElement extends Components.PwcIbox, HTMLStencilElement {}
  var HTMLPwcIboxElement: {
    prototype: HTMLPwcIboxElement;
    new (): HTMLPwcIboxElement;
  };

  interface HTMLPwcIboxContentElement extends Components.PwcIboxContent, HTMLStencilElement {}
  var HTMLPwcIboxContentElement: {
    prototype: HTMLPwcIboxContentElement;
    new (): HTMLPwcIboxContentElement;
  };

  interface HTMLPwcIboxFooterElement extends Components.PwcIboxFooter, HTMLStencilElement {}
  var HTMLPwcIboxFooterElement: {
    prototype: HTMLPwcIboxFooterElement;
    new (): HTMLPwcIboxFooterElement;
  };

  interface HTMLPwcIboxTitleElement extends Components.PwcIboxTitle, HTMLStencilElement {}
  var HTMLPwcIboxTitleElement: {
    prototype: HTMLPwcIboxTitleElement;
    new (): HTMLPwcIboxTitleElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-ibox': HTMLPwcIboxElement;
    'pwc-ibox-content': HTMLPwcIboxContentElement;
    'pwc-ibox-footer': HTMLPwcIboxFooterElement;
    'pwc-ibox-title': HTMLPwcIboxTitleElement;
  }
}

declare namespace LocalJSX {
  interface PwcIbox {}
  interface PwcIboxContent {}
  interface PwcIboxFooter {}
  interface PwcIboxTitle {}

  interface IntrinsicElements {
    'pwc-ibox': PwcIbox;
    'pwc-ibox-content': PwcIboxContent;
    'pwc-ibox-footer': PwcIboxFooter;
    'pwc-ibox-title': PwcIboxTitle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-ibox': LocalJSX.PwcIbox & JSXBase.HTMLAttributes<HTMLPwcIboxElement>;
      'pwc-ibox-content': LocalJSX.PwcIboxContent & JSXBase.HTMLAttributes<HTMLPwcIboxContentElement>;
      'pwc-ibox-footer': LocalJSX.PwcIboxFooter & JSXBase.HTMLAttributes<HTMLPwcIboxFooterElement>;
      'pwc-ibox-title': LocalJSX.PwcIboxTitle & JSXBase.HTMLAttributes<HTMLPwcIboxTitleElement>;
    }
  }
}


