/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";

export namespace Components {
  interface PwcIbox {
    closed: boolean;
  }
  interface PwcIboxContent {
    minimized: boolean;
  }
  interface PwcIboxFooter {
    minimized: boolean;
  }
  interface PwcIboxTitle {}
  interface PwcIboxTools {
    closeButton: boolean;
    minimizeButton: boolean;
  }
}

declare global {
  interface HTMLPwcIboxElement extends Components.PwcIbox, HTMLStencilElement {}
  var HTMLPwcIboxElement: {
    prototype: HTMLPwcIboxElement;
    new (): HTMLPwcIboxElement;
  };

  interface HTMLPwcIboxContentElement
    extends Components.PwcIboxContent,
      HTMLStencilElement {}
  var HTMLPwcIboxContentElement: {
    prototype: HTMLPwcIboxContentElement;
    new (): HTMLPwcIboxContentElement;
  };

  interface HTMLPwcIboxFooterElement
    extends Components.PwcIboxFooter,
      HTMLStencilElement {}
  var HTMLPwcIboxFooterElement: {
    prototype: HTMLPwcIboxFooterElement;
    new (): HTMLPwcIboxFooterElement;
  };

  interface HTMLPwcIboxTitleElement
    extends Components.PwcIboxTitle,
      HTMLStencilElement {}
  var HTMLPwcIboxTitleElement: {
    prototype: HTMLPwcIboxTitleElement;
    new (): HTMLPwcIboxTitleElement;
  };

  interface HTMLPwcIboxToolsElement
    extends Components.PwcIboxTools,
      HTMLStencilElement {}
  var HTMLPwcIboxToolsElement: {
    prototype: HTMLPwcIboxToolsElement;
    new (): HTMLPwcIboxToolsElement;
  };
  interface HTMLElementTagNameMap {
    "pwc-ibox": HTMLPwcIboxElement;
    "pwc-ibox-content": HTMLPwcIboxContentElement;
    "pwc-ibox-footer": HTMLPwcIboxFooterElement;
    "pwc-ibox-title": HTMLPwcIboxTitleElement;
    "pwc-ibox-tools": HTMLPwcIboxToolsElement;
  }
}

declare namespace LocalJSX {
  interface PwcIbox {
    closed?: boolean;
  }
  interface PwcIboxContent {
    minimized?: boolean;
  }
  interface PwcIboxFooter {
    minimized?: boolean;
  }
  interface PwcIboxTitle {}
  interface PwcIboxTools {
    closeButton?: boolean;
    minimizeButton?: boolean;
    onPwcIboxTools_closeClicked?: (event: CustomEvent<any>) => void;
    onPwcIboxTools_minimizeClicked?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    "pwc-ibox": PwcIbox;
    "pwc-ibox-content": PwcIboxContent;
    "pwc-ibox-footer": PwcIboxFooter;
    "pwc-ibox-title": PwcIboxTitle;
    "pwc-ibox-tools": PwcIboxTools;
  }
}

export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "pwc-ibox": LocalJSX.PwcIbox & JSXBase.HTMLAttributes<HTMLPwcIboxElement>;
      "pwc-ibox-content": LocalJSX.PwcIboxContent &
        JSXBase.HTMLAttributes<HTMLPwcIboxContentElement>;
      "pwc-ibox-footer": LocalJSX.PwcIboxFooter &
        JSXBase.HTMLAttributes<HTMLPwcIboxFooterElement>;
      "pwc-ibox-title": LocalJSX.PwcIboxTitle &
        JSXBase.HTMLAttributes<HTMLPwcIboxTitleElement>;
      "pwc-ibox-tools": LocalJSX.PwcIboxTools &
        JSXBase.HTMLAttributes<HTMLPwcIboxToolsElement>;
    }
  }
}
